const js = require('@eslint/js');
const globals = require('globals');

const prettier = require('eslint-plugin-prettier');
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended');

module.exports = [
  js.configs.recommended,
  eslintPluginPrettierRecommended,
  {
    plugins: {
      prettier
    },
    rules: {
      'prettier/prettier': ['error'],
      'no-var': ['error'],
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_'
        }
      ]
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.webextensions,
        ...globals.es2021,
        ...globals.jquery,
        ...globals.serviceworker
      }
    }
  },
  {
    // Ignores must be in a separate block to apply globally:
    // https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores
    ignores: [
      'eslint.config.js',
      '.repo/**/*',
      '_archive/**/*',
      '**/third-party/**',
      '**/node_modules/**/*',
      '**/dist/**/*',
      // These are autogenerated files that we shouldn't lint
      'functional-samples/cookbook.wasm-helloworld-print/wasm/pkg/**/*',
      'functional-samples/cookbook.wasm-helloworld-print-nomodule/wasm/pkg/**/*'
    ]
  }
];
